package com.phasitapp.rupost

const val KEY_USERS = "users"

const val KEY_POST = "post"
const val KEY_COMMENTS = "comments"
const val KEY_OPENID = "openId"
const val KEY_DATA = "data"
const val KEY_COMMENTS_LIKES = "comments_likes"
const val KEY_USERS_LIKE_COMMENTS = "users_like_comments"

const val KEY_EMAIL = "email"
const val KEY_UID = "uid"
const val KEY_USERNAME = "username"
const val KEY_LATITUDE = "latitude"
const val KEY_LONGITUDE = "longitude"
const val KEY_VIEWER = "viewer"
const val KEY_ID = "id"
const val KEY_CATEGORY = "category"
const val KEY_TARGET_GROUP = "targetGroup"
const val KEY_TITLE = "title"
const val KEY_DESCIPTION = "desciption"
const val KEY_ADDRESS = "address"
const val KEY_IMAGES = "images"
const val KEY_CREATEDATE = "createDate"
const val KEY_UPDATEDATE = "updateDate"
const val KEY_PROFILE = "profile"
const val KEY_LIKES = "likes"

const val KEY_MESSAGE = "message"

const val KEY_INFORMATION = "information"
const val KEY_USERCOUNT = "userCount"
const val KEY_EVENT = "event"
const val CATEGORY_QUESTION = "คำถาม"
const val CATEGORY_SHARE = "เเบ่งปัน"
const val CATEGORY_EVENT = "อีเว้นท์"
const val FILTERDAY_TODAY = "วันนี้"
const val FILTERDAY_YESTERDAY = "เมื่อวาน"
const val FILTERDAY_3DAY_LAST = "3 วันล่าสุด"
const val FILTERDAY_7DAY_LAST = "7 วันล่าสุด"

const val FOLDER_IMAGES = "images"
